#!/bin/sh

set -eu
if set -o | grep -q pipefail; then set -o pipefail; fi
set -x

D=$(readlink -f $(dirname $0))

for cfg_cmd in \
    'backuprc;source' \
    'bashrc;source' \
    'gdbinit;source' \
    '$include;inputrc' \
    'screenrc;source' \
    'tmux.conf;source-file' \
    'vimrc;source'; do
  cfg=${cfg_cmd%;*}
  cmd=${cfg_cmd#*;}
  echo "$cmd $D/$cfg" >> $HOME/.$cfg
done

cat >> $HOME/.gitconfig <<EOF
[include]
    path = $D/gitconfig
EOF

for f in $(cd $D && find .vim -type f); do
  mkdir -p $HOME/$(dirname $f)
  ln -s $D/$f $HOME/$f
done

echo "PATH=$D/bin:\$PATH" >> $HOME/.bashrc
